[package]
name = "hitbtc"
version = "0.1.0"
authors = ["Kaz Wesley <kaz@lambdaverse.org>"]

[dependencies]
actix = "0.5"
actix-web = { version = "0.6", features = ["alpn"] }
env_logger = "0.5"
futures = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio-core = "0.1"
