cargo-features = ["edition"]

[package]
name = "token"
version = "0.1.0"
authors = ["Kaz Wesley <kaz@lambdaverse.org>"]
edition = "2018"

[dependencies]
failure = "0.1"
failure_derive = "0.1"
serde = "1.0"
